language: node_js
node_js:
  - '10'

before_install:
  - npm install -g nyc
  - npm install -g mocha

install:
  - npm install

script:
  - npm run test_with_report

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
